### PR TITLE
Add race icons to player views

### PR DESCRIPTION
**Pull request by lennartblom**
**Addind race icons to following views**

• Player Stats Race Versus Race on Map
• Stats per race

Not sure about the icons, but I would like to propose highlighting the tables with some icons of each race. Due to existing assets, which seem to be official, I added theses files. Maybe we could add source section to communicate image licenses as gamepedia [1] did?

When adding theses files is alright, I can add some `.png` with smaller file size.

Screenshot 2020-06-21 at 12 58 26
Screenshot 2020-06-21 at 12 58 34

[1] https://wow.gamepedia.com/File:Warcraft_III_Reforged_-_Humans_Icon.png

### CODE REVIEW

**Comment by abeninski** [comment]
I think it looks good. Maybe @modmoto will know more about licensing

**Comment by modmoto** [comment]
i really like it on the player tab, on the stats tab it looks a little forced. Maybe Remove the "as Human" etc alltogether and just show the images? Make the "As Human" a hover also, then I guess it looks good.

**Comment by lennartblom** [comment]
Sure thing! 🙂 I’ll get on it!

**Comment by lennartblom** [comment]
Looking good 🙂 

Screenshot 2020-06-22 at 22 09 12

**Comment by lennartblom** [comment]
Rebased and squashed. ✅ 
I hope this can be declared as "merge"-material 🙂 

What do you think @abeninski, @modmoto? 🤔

**Comment by modmoto** [comment]
Hi Lennart,

Sorry, but I was on vacation until now and did not read this.

Looking good =) I like it.

**Comment by lennartblom** [comment]
Nice! Thanks a lot! Prod to get my work done! Thinking about some new stuff then 🙂

Hope your holiday was a blast! 🚀

Cheers

**Comment by modmoto** [comment]
I just saw on test, that maybe merge went bad? You want to take a look?

https://www.test.w3champions.com/player/modmoto%232809

**Pull request merged**
